config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#show'
  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  post 'entities', to: 'entities#create'
  get 'transactions', to: 'entities#index'
  get 'transactions/new', to: 'entities#new'
  get 'transactions/delete', to: 'entities#destroy'
  get 'external_transactions', to: 'entities#external_transactions'
  get 'external_transactions/assign', to: 'entities#assign'
  post '/external_transactions/external_transactions/assign', to: 'entities#call_assign'
  post 'groups', to: 'groups#create'
  get 'groups', to: 'groups#index'
  get 'groups/new', to: 'groups#new'
  get 'group/transactions', to: 'groups#transactions'
  get 'groups/delete', to: 'groups#destroy'
  resources :users do
    post 'edit', to: 'users#update'
    patch 'update', to: 'users#update'
  end
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :relations, dependent: :destroy
  has_many :groups, through: :relations
  validates :amount, presence: true
  validates :name, presence: true
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[assign_entity call_assign]
  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.user_id = current_user.id
    if @entity.save
      assign_entity
      flash[:notice] = 'New transaction created!'
    else
      flash[:alert] = 'Something went wrong!'
    end
    redirect_to transactions_path
  end

  def assign_entity
    current_user.groups.each do |group|
      next unless params[group.name] && !group.entities.include?(@entity)

      @relation = Relation.create!(entity_id: @entity.id, group_id: group.id)
      @entity.group_id = @entity.groups[0].id
      @entity.save
    end
  end

  def index; end

  def destroy
    @entity = Entity.find(params[:entity_id])
    if @entity.creator.id == current_user.id && @entity.destroy
      flash[:notice] = 'You have deleted this transaction!'
    else
      flash[:alert] = 'Something went wrong, please try again'
    end
    redirect_to transactions_path
  end

  def assign
    @relation = Relation.new
    @entity = Entity.new
  end

  def call_assign
    @entity = Entity.find(params[:entity_id])
    assign_entity
    flash[:notice] = 'Updated successfully!'
    redirect_to external_transactions_path
  end

  def external_transactions; end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/views/entities/assign.html.erb
<div class="container p-2">
  <h2 class="text-center white mb-4"> Select groups to assign </h2>
  <%= form_for(@relation, url: "external_transactions/assign?entity_id=#{params[:entity_id]}") do |form| %>
    <%= show_assigneable_groups %>
    <div class="container bottom-container d-flex justify-content-center">
      <%= form.submit 'Save', class: 'btn btn-outline-sucess bottom-link input-buttons', style: 'font-weight: 600;' %>
    </div>
  <% end %>
</div>

app/views/entities/external_transactions.html.erb
<div class="container p-2">
  <h2 class="text-center white mb-4"> All your external transactions </h2>
  <%= show_external_transactions %>
</div>

app/views/entities/index.html.erb
<div class="container p-2">
  <h2 class="text-center white mb-4"> All your transactions </h2>
  <div class="amount-box">
    <p class="text-center", style="font-weight: 600;"> Total: $ <%= show_total_spent %> </p>
  </div>
  <%= show_transactions %>
  <div class="container bottom-container d-flex justify-content-center">
    <%= link_to 'New Transaction', transactions_new_path, class:'bottom-link btn btn-outline-success' %>
  </div>
</div>

app/views/entities/new.html.erb
<h1 class="text-center white mt-4 mb-4"> New Transaction </h1>
  <div class="container text-center p-2">
    <%= form_for(@entity) do |form| %>
      <%= form.label :name, class:'text-center white w-100 mb-3', style:'font-weight: 600;' %>
      <%= form.text_field :name, id:"name", class: 'form-control mb-3 text-center', placeholder: 'Name' %>
      <%= form.label :amount, class:'text-center white w-100 mb-3', style:'font-weight: 600;' %>
      <%= form.text_field :amount, id:"amount", class: 'form-control mb-3 text-center', placeholder: 'i.e: 20.57' %>
      <%= form.label :groups, class:'text-center white w-100 mb-3', style:'font-weight: 600;' %>
      <%= groups_text %>
      <%= show_assigneable_groups %>
      <div class="container bottom-container d-flex justify-content-center">
        <%= form.submit 'Save', class: 'btn btn-outline-sucess bottom-link input-buttons', style: 'font-weight: 600;' %>
      </div>
    <% end %>
  </div>