config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#show'
  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  post 'entities', to: 'entities#create'
  get 'transactions', to: 'entities#index'
  get 'transactions/new', to: 'entities#new'
  get 'transactions/delete', to: 'entities#destroy'
  get 'external_transactions', to: 'entities#external_transactions'
  get 'external_transactions/assign', to: 'entities#assign'
  post '/external_transactions/external_transactions/assign', to: 'entities#call_assign'
  post 'groups', to: 'groups#create'
  get 'groups', to: 'groups#index'
  get 'groups/new', to: 'groups#new'
  get 'group/transactions', to: 'groups#transactions'
  get 'groups/delete', to: 'groups#destroy'
  resources :users do
    post 'edit', to: 'users#update'
    patch 'update', to: 'users#update'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :relations, dependent: :destroy
  has_many :entities, through: :relations
  has_one_attached :image, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: true }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      flash[:notice] = 'New Group created!'
    else
      flash[:alert] = 'Something went wrong!'
    end
    redirect_to groups_path
  end

  def transactions
    @group = Group.find(params[:id])
  end

  def index; end

  def destroy
    @group = Group.find(params[:group_id])
    @group.relations.each do |relation|
      entity = Entity.find(relation.entity_id)
      entity.group_id = nil
      entity.save
    end
    if @group.creator.id == current_user.id && @group.destroy
      flash[:notice] = 'Group deleted successfully!'
    else
      flash[:alert] = 'Something went wrong!'
    end
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :image)
  end
end

app/helpers/group_helper.rb
# rubocop:disable Layout/LineLength
module GroupHelper
  def show_groups
    content = ''
    current_user.groups.each do |group|
      content +=
        "<a href='/group/transactions?id=#{group.id}', class='groups w-75'><div class='card d-flex flex-row'>
          <div class='card-body justify-content-flex-end d-flex'>
            <img #{group_img_path(group)}, class='group-image' %>
            <h5 class='card-title w-75'>#{group.name}</h5>
          </div>
          <div class='card-body'>
            <p class='card-text'>Transactions: #{group.entities.length}</p>
            <a href='/groups/delete?group_id=#{group.id}', class='groups btn btn-success', method: :delete, data-confirm='Are you sure to delete this item?'>Delete</a>
          </div>
        </div></a>"
    end
    content.html_safe
  end

  def show_assigneable_groups
    content = ''
    current_user.groups.each do |group|
      content +=
        "<div class='card d-flex flex-row'>
          <div class='card-body w-100 d-flex align-items-center'>
            <input type='checkbox', name='#{group.name}', value='#{group.id}', { multiple: true }, id='checkbox'>
            <img #{group_img_path(group)}, class='group-image ml-2 mr-2' %>
            <h5 class='card-title w-75'>#{group.name}</h5>
          </div>
          <div class='card-body'>
            <p class='card-text'>Transactions: #{group.entities.length}</p>
          </div>
        </div>"
    end
    content.html_safe
  end

  def show_group_transactions
    content = ''
    transactions = @group.entities.sort { |a, b| b <=> a }
    transactions.each do |entity|
      content +=
        "<div class='card d-flex flex-row'>
      <div class='card-body w-50'>
        <div class='w-100 d-flex'>
          <img #{entity_img_path(entity)}, class='group-image' %>
          <h5 class='card-title w-75'>#{entity.name}</h5>
        </div>
        <p class='card-text'>#{entity.created_at}</p>
      </div>
      <div class='card-body'>
        <p class='card-text', style='font-weight: bolder;'>$ #{entity.amount}</p>
        <a href='/external_transactions/assign?entity_id=#{entity.id}', class='groups btn btn-success'>Re-assign</a>
      </div>
    </div>"
    end
    content.html_safe
  end
end
# rubocop:enable Layout/LineLength

app/views/groups/index.html.erb
<div class="container p-2">
  <h2 class="text-center white mb-4"> All your groups </h2>
  <%= show_groups %>
  <div class="container bottom-container d-flex justify-content-center">
    <%= link_to 'New Group', groups_new_path, id: 'New Group', class:'bottom-link btn btn-outline-success' %>
  </div>
</div>

app/views/groups/new.html.erb
<h1 class="text-center white mt-4 mb-4"> New Group </h1>
  <div class="container text-center p-2">
    <%= form_for(@group) do |form| %>
      <div class="control-label col w-100 mb-3 justify-content-center white">
        <%= form.label "Profile picture", class:'text-center white mb-2' %>
        <%= form.file_field :image %>
      </div>
      <%= form.label :name, class:'text-center white w-100 mb-3', style:'font-weight: 600;' %>
      <%= form.text_field :name, id:"name", class: 'form-control mb-3 text-center', placeholder: 'Name' %>
      <div class="container bottom-container d-flex justify-content-center">
        <%= form.submit 'Save', class: 'btn btn-outline-sucess bottom-link input-buttons', style: 'font-weight: 600;' %>
      </div>
    <% end %>
  </div>

app/views/groups/transactions.html.erb
<div class="container p-2">
  <h2 class="text-center white mb-4 text-overflow"> All <%= @group.name %>'s transactions </h2>
  <%= show_group_transactions %>
  <div class="container bottom-container d-flex justify-content-center">
    <%= link_to 'Back to groups', groups_path, class:'bottom-link btn btn-outline-success' %>
  </div>
</div>