config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#show'
  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  post 'entities', to: 'entities#create'
  get 'transactions', to: 'entities#index'
  get 'transactions/new', to: 'entities#new'
  get 'transactions/delete', to: 'entities#destroy'
  get 'external_transactions', to: 'entities#external_transactions'
  get 'external_transactions/assign', to: 'entities#assign'
  post '/external_transactions/external_transactions/assign', to: 'entities#call_assign'
  post 'groups', to: 'groups#create'
  get 'groups', to: 'groups#index'
  get 'groups/new', to: 'groups#new'
  get 'group/transactions', to: 'groups#transactions'
  get 'groups/delete', to: 'groups#destroy'
  resources :users do
    post 'edit', to: 'users#update'
    patch 'update', to: 'users#update'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entities, dependent: :destroy
  has_many :groups
  has_many :external_transactions, -> { where group_id: nil }, class_name: 'Entity'
  has_one_attached :image, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: %i[edit update show destroy]
  skip_before_action :verify_authenticity_token, only: [:update]
  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to Finance Control #{@user.username}"
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_path if current_user.id != @user.id
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:notice] = 'Your account was updated successfully'
      redirect_to root_path
    else
      flash[:alert] = 'Username already taken!'
      render 'edit'
    end
  end

  def show
    @user = User.find(current_user.id)
  end

  def destroy
    @user = User.find(current_user.id)
    if @user.destroy
      flash[:notice] = 'You have deleted your account!'
    else
      flash[:alert] = 'Something went wrong, please try again'
      redirect_to root_path
    end
  end

  private

  def authenticate
    redirect_to login_path unless logged_in?
  end

  def user_params
    params.require(:user).permit(:username, :image)
  end
end

app/views/users/edit.html.erb
<h1 class="text-center white mt-4 mb-4">Edit profile</h1>
<div class="row">
  <div class="col">
    <%= form_for(@user, :html => {class: "form-horizontal w-100", role: "form"}, url: edit_user_path(@user.id), method: :update) do |f| %>
      <div class='container text-center p-2'>
        <div class="form-group">
          <div class="control-label col w-100 mb-3 justify-content-center white">
            <%= f.label "Profile picture", class:'text-center white mb-2' %>
            <%= f.file_field :image %>
          </div>
          <div class="control-label col-sm-2 w-100">
            <%= f.label :username, class:'text-center white w-100 mb-3' %>
          </div>
          <div class="col-sm-8 w-100 d-flex justify-content-center mt-3 mb-3">
            <%= f.text_field :username, class: 'form-control mb-3 text-center', placeholder: "Enter username", autofocus: true %>
          </div>
        </div>
        <div class="form-group w-100">
          <div class="container bottom-container d-flex justify-content-center">
            <%= f.submit 'Update Account', class: 'btn btn-outline-sucess bottom-link input-buttons', style: 'font-weight: 600;' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center white mt-4 mb-4">SIGN UP</h1>
<div class="row">
  <div class="col">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}, url: signup_path) do |f| %>
      <div class='container text-center p-2'>
        <div class="form-group">
          <div class="control-label col w-100 mb-3 justify-content-center white">
            <%= f.label "Profile picture", class:'text-center white mb-2' %>
            <%= f.file_field :image %>
          </div>
          <div class="control-label col-sm-2 w-100">
            <%= f.label :username, class:'white' %>
          </div>
          <div class="col-sm-8 w-100 d-flex justify-content-center mt-3 mb-3">
            <%= f.text_field :username, class: "form-control w-75", placeholder: "Enter username", autofocus: true %>
          </div>
        </div>
        <div class="form-group w-100">
          <div class="container bottom-container d-flex justify-content-center">
            <%= f.submit 'Create Account', class: 'btn btn-outline-sucess bottom-link input-buttons', style: 'font-weight: 600;' %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="col text-center mt-2">
      <%= link_to 'Already have an account? Log In!', login_path %>
    </div> 
  </div>
</div>

app/views/users/show.html.erb
<div class='w-100 d-flex justify-content-center'>
  <%= image_tag profile_img_path, class:'user-image mt-3' %>
</div>
<h5 class="text-center white mb-3 pb-3 mt-2"><%= @user.username %></h5>
<div class="container w-100">
  <div class="col p-4">
    <div class="row left-menu-item title pb-2">
      <i class="fas fa-cog icon"></i>
      <%= link_to 'Edit account', edit_user_path(current_user.id), class:'link' %>
    </div>
    <div class="row left-menu-item title pb-2">
      <i class="fas fa-cash-register icon"></i>
      <%= link_to 'All my transactions', transactions_path, class:'link' %>
    </div>
    <div class="row left-menu-item title pb-2">
      <i class="far fa-money-bill-alt icon"></i>
      <%= link_to 'All my external transactions', external_transactions_path, class:'link' %>
    </div>
    <div class="row left-menu-item title pb-2">
      <i class="fas fa-layer-group icon"></i>
      <%= link_to 'All groups', groups_path, class:'link' %>
    </div>
    <div class="row left-menu-item title pb-2">
      <i class="fas fa-sign-out-alt icon"></i>
      <%= link_to 'Logout', logout_path, class:'link' %>
    </div>
  </div>
</div>